ALTER TABLE "BillItem" ADD COLUMN "hsn" VARCHAR(12) NOT NULL DEFAULT '85269190';
ALTER TABLE "BillItem" ADD COLUMN "per" VARCHAR(10) NOT NULL DEFAULT 'PCS';
ALTER TABLE "BillItem" ADD COLUMN "rateInclTax" DECIMAL(10,2) NOT NULL DEFAULT 0;
ALTER TABLE "BillItem" ADD COLUMN "discPercent" DECIMAL(5,2) NOT NULL DEFAULT 0;

UPDATE "BillItem" SET "rateInclTax" = ROUND("amount" * 1.18, 2) WHERE "rateInclTax" = 0;
